name: Self-Hosted Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Tells GitHub to look for your EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Deployment Script
        run: |
          # This runs DIRECTLY on your EC2 terminal
          sudo docker run -d -p 80:80 --name self-hosted-web nginx || sudo docker start self-hosted-web
